
// This file was automatically generated by the CoreABC TGI generator

  parameter APB_DWIDTH           = 16;
  parameter APB_SDEPTH           = 7;
  parameter APB_AWIDTH           = 12;
  parameter ICWIDTH              = 12;
  parameter ZRWIDTH              = 16;
  parameter IIWIDTH              = 4;
  parameter IFWIDTH              = 4;
  parameter IOWIDTH              = 1;
  parameter STWIDTH              = 8;
  parameter INITWIDTH            = 16;
  parameter INSMODE              = 0;
  parameter IMEM_APB_ACCESS      = 0;
  parameter ACT_CALIBRATIONDATA  = 1;
  parameter EN_RAM               = 1;
  parameter EN_RAM_ECC           = 0;
  parameter EN_ALURAM            = 1;
  parameter EN_INDIRECT          = 1;
  parameter EN_DATAM             = 2;
  parameter EN_INT               = 2;
  parameter ISRADDR              = 1;
  parameter EN_AND               = 1;
  parameter EN_XOR               = 1;
  parameter EN_OR                = 1;
  parameter EN_ADD               = 1;
  parameter EN_INC               = 1;
  parameter EN_SHL               = 1;
  parameter EN_SHR               = 1;
  parameter EN_CALL              = 1;
  parameter EN_PUSH              = 1;
  parameter EN_ACM               = 1;
  parameter EN_IOREAD            = 1;
  parameter EN_IOWRT             = 1;
  parameter EN_MULT              = 0;
  parameter HDL_license          = "U";
  parameter UNIQ_STRING_LENGTH   = 21;
  parameter UNIQ_STRING          = "Minimal_SoC_COREABC_0";
  parameter TESTMODE             = 0;
  parameter FAMILY               = 15;
  parameter ID                   = 0;
  parameter MAX_NVMDWIDTH        = 32;
  parameter TESTBENCH            = "User";
  parameter DEBUG                = 1;


